# For OCI Dynanic Flexible Load Balancer
#controller:
#  service:
#    type: LoadBalancer

#service:
#  type: LoadBalancer
#  annotations:
#    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
#    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
#    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
#    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.sa-saopaulo-1......"
exampleValue: common-chart
