apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-azure-credentials
  namespace: security
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: velero-azure-credentials
  dataFrom:
    - extract:
        key: velero-azure-credentials 