apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: viine-skt-nonprod #alterar
  namespace: argocd
spec:
  project: nonprod
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.1.1
    helm:
      values: |-
        image:
          repository: tallerwillianalmeida/sktbr #alterar
          tag: "2200_main" #alterar
        replicaCount: 2
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
            external-dns.alpha.kubernetes.io/hostname: guiadodevops.com
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
            - host: viine-skt-nonprod.guiadodevops.com #alterar
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: viine-skt-nonprod-tls #alterar
            hosts:
              - viine-skt-nonprod.guiadodevops.com #alterar
    chart: core/myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    automated: {}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true