apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtube-converter-nonprod
  namespace: argocd
spec:
  project: nonprod
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.1.0
    helm:
      values: |-
        image:
          repository: ghcr.io/ndawpa/youtube-converter
          pullPolicy: IfNotPresent
          tag: "sha-5b36687"

        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
            external-dns.alpha.kubernetes.io/hostname: youtube-converter-nonprod.guiadodevops.com
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
            - host: youtube-converter-nonprod.guiadodevops.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: youtube-converter-tls
              hosts:
                - youtube-converter-nonprod.guiadodevops.com
        persistence:
          enabled: false
    chart: core/youtube-converter
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=background
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true