apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-azure-credentials
  namespace: airflow
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: airflow-azure-credentials
  dataFrom:
    - extract:
        key: airflow-azure-credentials
  data:
    - secretKey: connection-string
      remoteRef:
        key: airflow-azure-credentials
        property: connection-string
    - secretKey: account-key
      remoteRef:
        key: airflow-azure-credentials
        property: account-key 