apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-connections
  namespace: airflow
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: airflow-connections
  dataFrom:
    - extract:
        key: airflow-connections