apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-passwords
  namespace: security
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-passwords
  dataFrom:
    - extract:
        key: keycloak-passwords