apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 9.2.10
    chart: infra/opentelemetry-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
