apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-distributed
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 1.46.1
    chart: infra/tempo-distributed
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
