apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 36.3.0
    chart: infra/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
