apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 36.3.0
    helm:
      values: |-
        service:
          annotations:
            service.beta.kubernetes.io/oci-load-balancer-shape: flexible
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    chart: infra/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
